syntax on
set number
set nowrap

""" TABBING
set expandtab
set tabstop=2
set shiftwidth=2

""" LINE WIDTH
set colorcolumn=0
match ErrorMsg '\%>120v.\+'

""" AUTOSAVE
:au FocusLost * silent! wa

""" LAST POSITION
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe
  "normal! g'\"" | endif
endif

filetype on
set nocompatible

set hidden
nnoremap <C-E> :e.<CR>
nnoremap <C-N> :bnext<CR>
nnoremap <C-P> :bprev<CR>
nnoremap <C-W> :bw<CR>

syntax on
colorscheme basic-light

